ovs                                            opt/OpenvStorage
config/env/ovs.sh                              etc/profile.d
config/logrotate/openvstorage-logs             etc/logrotate.d
config/templates                               opt/OpenvStorage/config
scripts/install/openvstorage-core.postinst.py  opt/OpenvStorage/scripts/install
scripts/system/ovs                             usr/bin
scripts/system/openvstorage                    etc/bash_completion.d
scripts/system/rotate-storagedriver-logs.sh    opt/OpenvStorage/scripts/system
