ovs                                            opt/OpenvStorage
config/elk/indexer.conf                        etc/logstash/conf.d
config/elk/elasticsearch.yml                   opt/OpenvStorage/config
config/main.cfg                                opt/OpenvStorage/config
config/templates                               opt/OpenvStorage/config
scripts/install/openvstorage-core.postinst.py  opt/OpenvStorage/scripts/install
